### ISSUE TITLE
Mute action shows "steps" instead of percentage for current volume

### ISSUE THREAD

**Issue by bioxz** [G4PLS/AudioControl#3]
I'm using the Mute action for my audio device (Device Filter set to Output Device and the device is selected) and muting works fine. I also have the Show Info option enabled to see my current volume. Right now the action shows, instead of the volume percentage I'm used to, a number between 0 and 19. My Plasma audio is set to step in 5% steps, so the number is actually the current "step" I'm in instead of the actual percentage. Sometimes the action works as expected, sometimes if shows these steps instead.

Edit: While testing if it actually goes down to 0 to stops at 1 it just fixed itself. After getting to 0 once, it's now showing the percentage again.

**Comment by G4PLS** [comment]
I dont think there is a lot I can do there. All the information i get about volume comes directly from Pulse and i then use that Information do display the volume
Sadly I cant reproduce it because I dont even know where pulse gets that Info
