### ISSUE TITLE
Feature request: Perform actions on currently active output/input device

### ISSUE THREAD

**Issue by mpwaldhorst** [G4PLS/AudioControl#7]
When setting up actions it would be nice not to have to choose a specific audio device but rather rely on the currently active output or input device that the system/OS is using.

This would give some flexibility where you can have a button switch the output device and the mute button keep working instead of having to add multiple mute buttons etc.

Would this be something that can be added in the future? Or is this already possible and am I just missing something?

**Comment by G4PLS** [comment]
What do you mean with the currently used input/output device? Do you mean the set standard device because this would be something that is probably doable.

Setting stuff for an actual used device is not really possible because from the system every device is being used

**Comment by mpwaldhorst** [comment]
Thanks for the quick response.

I think that is indeed what I'm referring to. Just to be sure I basically mean the device that is either selected in the Gnome action menu:
![image](https://github.com/user-attachments/assets/892be546-5654-41a2-9ea7-f08576835765)

Or in the settings under Sound:
![image](https://github.com/user-attachments/assets/0037f337-fd47-4dad-b51c-f49cac83e430)

I think that might have some nice synergy with the Audio Switcher plugin.

**Comment by G4PLS** [comment]
I think thats the default device, so we mean the same thing.

Adding this wouldnt be that hard, will add that in the future!

**Comment by G4PLS** [comment]
Within the next 1-2 weeks I will roll out a new update of the Plugin, in there I will add this feature of the Standard device controls

**Comment by G4PLS** [comment]
Standard device support is now added aswell
You will need to wait until beta.7 releases as some features are not available in the pre-release

**Comment by G4PLS** [comment]
With the latest update this is now a feature so this issue will be closed
If there are any other issues with the Plugin you need to create a new Issue

**Comment by mpwaldhorst** [comment]
Thank you for the update!
